apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes2.default.svc
      - git:
          repoURL: https://github.com/a-kaplun/appsets-example.git
          revision: main
          directories:
          - path: 'apps/*/envs/{{.cluster}}'
  template:      
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/a-kaplun/appsets-example.git
        targetRevision: main
        path: '{{.path.path}}'      
      destination:
        server: '{{.url}}'
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
