apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/a-kaplun/appsets-example.git
      revision: main
      directories:
      - path: apps/*/envs/dev
  template:      
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/a-kaplun/appsets-example.git
        targetRevision: main
        path: '{{.path.path}}'      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
